# import requests
#
# parameters = {
#     "amount":10,
#     "category":18,
#     "type":"boolean"
#
# }
#
#
# data = requests.get("https://opentdb.com/api.php", params=parameters)
# data.raise_for_status()
# quest = data.json()
#
# quqestion_data = quest["results"]
# print(quest["results"])


question_data = [{
    "question0":"Geschlecht",
    "correct_answer":"True"
},{"question1":"Beziehungen",
    "correct_answer":"True"},
    {"question2":"Staatsangehörigkeit",
    "correct_answer":"True"},
    {"question3":"Herkunft",
    "correct_answer":"True"},
    {"question4": "Tagesblauf",
     "correct_answer": "True"},
    {"question5":"Gewohnheiten",
    "correct_answer":"True"},
    {"question6":"Einrichtungen",
    "correct_answer":"True"},
    {"question7":"Miete",
    "correct_answer":"True"},
    {"question8":"Mietverhaltnis",
    "correct_answer":"True"},
    {"question9":"Wohnungswechsel",
     "correct_answer":"True"},
    {"question10":"Öffentlicher verkehr",
     "correct_answer":"True"},
    {"question11":"Unterkunft",
     "correct_answer":"True"},
    {"question12":"Nahrungsmittel",
     "correct_answer":"True"},
    {"question13":"Mahlzeiten",
     "correct_answer":"True"},
    {"question14":"Lebensmittel",
     "correct_answer":"True"},
    {"question15":"Betreuung",
     "correct_answer":"True"},
    {"question16":"Sport treiben",
     "correct_answer":"True"},
    {"question17":"Lektüre",
     "correct_answer":"True"},
    {"question18":"ein grad",
     "correct_answer":"True"},
    {"question19":"2 Quadratmeter",
     "correct_answer":"True"},
    {"question20":"zwei hoch drei",
     "correct_answer":"True"},
    {"question21":"Was darf ich dir anbieten?hat angeboten",
     "correct_answer":"True"},
    {"question22":"die Ankunft",
     "correct_answer":"True"},
    {"question23":"sich Anmelden. Hat Angemeldet",
     "correct_answer":"True"},
    {"question24":"die Anrede, der Gruss",
     "correct_answer":"True"},
    {"question25":"die Ansage",
     "correct_answer":"True"},
    {"question26":"der Anschluss",
     "correct_answer":"True"},
    {"question27":"fehlen",
     "correct_answer":"True"},
    {"question28":"der Anschluss",
     "correct_answer":"True"},
    {"question29":"die Auskunft",
     "correct_answer":"True"},
    {"question30":"die Beamtin",
     "correct_answer":"True"},
    {"question31":"bedeuten",
     "correct_answer":"True"},
    {"question32":"beide",
     "correct_answer":"True"},
    {"question33":"bekannt",
     "correct_answer":"True"},
    {"question34":"der Beruf",
     "correct_answer":"True"},
    {"question35":"besetzt",
     "correct_answer":"True"},
    {"question36":"Besichtigen, hat besichtigt",
     "correct_answer":"True"},
    {"question37":"leise",
     "correct_answer":"True"},
    {"question38":"der Blick",
     "correct_answer":"True"},
    {"question39":"Böse",
     "correct_answer":"True"},
    {"question40":"breit",
     "correct_answer":"True"},
    {"question41":"der Brief",
     "correct_answer":"True"},
    {"question42":"dauern",
     "correct_answer":"True"},
    {"question43":"draussen",
     "correct_answer":"True"},
    {"question44":"drück",
     "correct_answer":"True"},
    {"question45":"die Durchsage",
     "correct_answer":"True"},
    {"question46":"eilig",
     "correct_answer":"True"},
    {"question47":"der Eintritt",
     "correct_answer":"True"},
    {"question48":"der Empfänger",
     "correct_answer":"True"},
    {"question49":"empfehlen",
     "correct_answer":"True"},
    {"question50":"das Ergebnis",
     "correct_answer":"True"},
    {"question51":"erlauben",
     "correct_answer":"True"},
    {"question52":"der Erwachsene",
     "correct_answer":"True"},
    {"question53":"ledig",
     "correct_answer":"True"},
    {"question54":"fehlen",
     "correct_answer":"True"},
    {"question55":"das Feuer",
     "correct_answer":"True"},
    {"question56":"deshalb",
     "correct_answer":"True"},
    {"question57":"fremd",
     "correct_answer":"True"},
    {"question58":"Die Führung",
     "correct_answer":"True"},
    {"question59":"fremd",
     "correct_answer":"True"},
    {"question60":"gehören",
     "correct_answer":"True"},
    {"question61":"das Gespräch",
     "correct_answer":"True"},
    {"question62":"das Gewicht",
     "correct_answer":"True"},
    {"question63":"anhalten",
     "correct_answer":"True"},
    {"question64":"Gleis 12",
     "correct_answer":"True"},
    {"question65":"gültig",
     "correct_answer":"True"},
    {"question66":"Bekannt",
     "correct_answer":"True"},
    {"question67":"Kunde",
     "correct_answer":"True"},
    {"question68":"der Kollege",
     "correct_answer":"True"},
    {"question69":"überweisen",
     "correct_answer":"True"},
    {"question70":"kriegen",
     "correct_answer":"True"},
    {"question71":"sich kümmern",
     "correct_answer":"True"},
    {"question72":"legen",
     "correct_answer":"True"},
    {"question73":"der Lkw",
     "correct_answer":"True"},
    {"question74":"das Lokal",
     "correct_answer":"True"},
    {"question75":"lustig",
     "correct_answer":"True"},
    {"question76":"möglich",
     "correct_answer":"True"},
    {"question77":"das ist in Ordnung",
     "correct_answer":"True"},
    {"question78":"Postleitzahl",
     "correct_answer":"True"},
    {"question79":"rauchen",
     "correct_answer":"True"},
    {"question80":"riechen",
     "correct_answer":"True"},
    {"question81":"das Schild",
     "correct_answer":"True"},
    {"question82":"der Schluss",
     "correct_answer":"True"},
    {"question83":"die Sehenswürdigkeit",
     "correct_answer":"True"},
    {"question84":"rauchen",
     "correct_answer":"True"},
    {"question85":"selbständig",
     "correct_answer":"True"},
    {"question86":"Ich habe eine neue stelle",
     "correct_answer":"True"},
    {"question87":"stell das Buch",
     "correct_answer":"True"},
    {"question88":"die Treppe",
     "correct_answer":"True"},
    {"question89":"tun",
     "correct_answer":"True"},
    {"question90":"unterschreiben",
     "correct_answer":"True"},
    {"question91":"verdienen",
     "correct_answer":"True"},
    {"question92":"der Verein, Sportverein",
     "correct_answer":"True"},
    {"question93":"der Verwandte",
     "correct_answer":"True"},
    {"question94":"die Vorsicht",
     "correct_answer":"True"},
    {"question95":"sich vorstellen",
     "correct_answer":"True"},
    {"question96":"die Vorwahl",
     "correct_answer":"True"},
    {"question97":"weiblich",
     "correct_answer":"True"},
    {"question98":"weit",
     "correct_answer":"True"},
    {"question99":"wichtig",
     "correct_answer":"True"},
    {"question100":"der Wind",
     "correct_answer":"True"},
    {"question101":"zurzeit",
     "correct_answer":"True"},
    {"question102":"der Zoll",
     "correct_answer":"True"},
    {"question103":"zufrieden",
     "correct_answer":"True"},
    {"question104":"um Mitternacht",
     "correct_answer":"True"},
    {"question105":"am Nachmittag",
     "correct_answer":"True"},
    {"question106":"am Mittwoch",
     "correct_answer":"True"},
    {"question107":"schaffe",
     "correct_answer":"True"},
    {"question108":"fängt an, hat angefangen",
     "correct_answer":"True"},
    {"question109":"hat angekommen, ankommen",
     "correct_answer":"True"},
    {"question110":"ansehen. Hat angesehen",
     "correct_answer":"True"},
    {"question111":"arm",
     "correct_answer":"True"},
    {"question112":"Auf jeden Fall",
     "correct_answer":"True"},
    {"question113":"Aufpassen, hat aufgepasst",
     "correct_answer":"True"},
    {"question114":"aufräumen, hat aufgeräumt",
     "correct_answer":"True"},
    {"question115":"Aufpassen, hat aufgepasst",
     "correct_answer":"True"},
    {"question116":"Ausruhen, hat ausgeruht",
     "correct_answer":"True"},
    {"question117":"Aussehen, hat ausgesehen",
     "correct_answer":"True"},
    {"question118":"Ausser, Ausserdem",
     "correct_answer":"True"},
    {"question119":"Aussprechen, hat ausgesprochen",
     "correct_answer":"True"},
    {"question120":"die Austellung",
     "correct_answer":"True"},
    {"question121":"Austragen, hat Ausgetragen",
     "correct_answer":"True"},
    {"question122":"Baden, hat gebadet",
     "correct_answer":"True"},
    {"question123":"Die Kinder haben etwas gebastellt",
     "correct_answer":"True"},
    {"question124":"Bauen, hat gebaut",
     "correct_answer":"True"},
    {"question125":"beeilen sich, hat beeilt",
     "correct_answer":"True"},
    {"question126":"beeilen sich, hat beeilt",
     "correct_answer":"True"},
    {"question127":"Du musst deine Ausbildung auf jeden Fall beenden. Hat beendet",
     "correct_answer":"True"}
    {"question128":"Begründen. Hat begründet",
     "correct_answer":"True"},
    {"question129":"Beraten. Hat berat",
     "correct_answer":"True"},
    {"question130":"Berichten. Hat berichtet",
     "correct_answer":"True"},
    {"question131":"der Bescheid",
     "correct_answer":"True"},
    {"question132":"Beschreiben, hat beschrieben",
     "correct_answer":"True"},
    {"question133":"Beschweren, hat beschwert",
     "correct_answer":"True"},
    {"question134":"Bestätigen, hat bestätigt",
     "correct_answer":"True"},
    {"question135":"Bestehen, hat bestanden",
     "correct_answer":"True"},
    {"question136":"Bewerben um, hat beworben",
     "correct_answer":"True"},
    {"question137":"das Blatt",
     "correct_answer":"True"},
    {"question138":"blöd",
     "correct_answer":"True"},
    {"question139":"Ich habe dein Buch vergessen. Hoffentlich bist du mir nicht böse.",
     "correct_answer":"True"},
    {"question140":"Die Bohne",
     "correct_answer":"True"},
    {"question141":"Braten, hat gebraten",
     "correct_answer":"True"},
    {"question142":"Morgen buche ich unsere Urlaubsreise. Hat gebucht",
     "correct_answer":"True"},
    {"question143":"Diesen Buchstaben gibt es in meiner Sprache nicht. ",
     "correct_answer":"True"},
    {"question144":"Bunt ",
     "correct_answer":"True"}
]

#
# qquestion_data = [
#     {
#         "category": "Science: Computers",
#         "type": "boolean",
#         "difficulty": "medium",
#         "question": "The HTML5 standard was published in 2014.",
#         "correct_answer": "True",
#         "incorrect_answers": [
#             "False"
#         ]
#     },
#     {
#         "category": "Science: Computers",
#         "type": "boolean",
#         "difficulty": "medium",
#         "question": "The first computer bug was formed by faulty wires.",
#         "correct_answer": "False",
#         "incorrect_answers": [
#             "True"
#         ]
#     },
#     {
#         "category": "Science: Computers",
#         "type": "boolean",
#         "difficulty": "medium",
#         "question": "FLAC stands for 'Free Lossless Audio Condenser'.",
#         "correct_answer": "False",
#         "incorrect_answers": [
#             "True"
#         ]
#     },
#     {
#         "category": "Science: Computers",
#         "type": "boolean",
#         "difficulty": "medium",
#         "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
#         "correct_answer": "False",
#         "incorrect_answers": [
#             "True"
#         ]
#     },
#     {
#         "category": "Science: Computers",
#         "type": "boolean",
#         "difficulty": "easy",
#         "question": "Linus Torvalds created Linux and Git.",
#         "correct_answer": "True",
#         "incorrect_answers": [
#             "False"
#         ]
#     },
#     {
#         "category": "Science: Computers",
#         "type": "boolean",
#         "difficulty": "easy",
#         "question": "The programming language 'Python' is based off a modified version of 'JavaScript'",
#         "correct_answer": "False",
#         "incorrect_answers": [
#             "True"
#         ]
#     },
#     {
#         "category": "Science: Computers",
#         "type": "boolean",
#         "difficulty": "medium",
#         "question": "AMD created the first consumer 64-bit processor.",
#         "correct_answer": "True",
#         "incorrect_answers": [
#             "False"
#         ]
#     },
#     {
#         "category": "Science: Computers",
#         "type": "boolean",
#         "difficulty": "easy",
#         "question": "'HTML' stands for Hypertext Markup Language.",
#         "correct_answer": "True",
#         "incorrect_answers": [
#             "False"
#         ]
#     },
#     {
#         "category": "Science: Computers",
#         "type": "boolean",
#         "difficulty": "easy",
#         "question": "In most programming languages, the operator ++ is equivalent to the statement '+= 1'.",
#         "correct_answer": "True",
#         "incorrect_answers": [
#             "False"
#         ]
#     },
#     {
#         "category": "Science: Computers",
#         "type": "boolean",
#         "difficulty": "hard",
#         "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
#         "correct_answer": "False",
#         "incorrect_answers": [
#             "True"
#         ]
#     }
# ]
