{'question0': 'Geschlecht', 'correct_answer': 'True'},
{'question1': 'Was darf ich dir anbieten?', 'correct_answer': 'True'},
{'question2': 'die Ankunft', 'correct_answer': 'True'},
{'question3': 'sich Anmelden', 'correct_answer': 'True'},
{'question4': 'die Ansage', 'correct_answer': 'True'},
{'question5': 'der Anschluss', 'correct_answer': 'True'},
{'question6': 'fehlen', 'correct_answer': 'True'},
{'question7': 'der Anschluss', 'correct_answer': 'True'},
{'question8': 'die Auskunft', 'correct_answer': 'True'},
{'question9': 'die Beamtin', 'correct_answer': 'True'},
{'question10': 'bedeutet', 'correct_answer': 'True'},
{'question11': 'bekannt', 'correct_answer': 'True'},
{'question12': 'der Beruf', 'correct_answer': 'True'},
{'question13': 'besetzt', 'correct_answer': 'True'},
{'question14': 'Besichtigen', 'correct_answer': 'True'},
{'question15': 'der Blick', 'correct_answer': 'True'},
{'question16': 'breit', 'correct_answer': 'True'},
{'question17': 'der Brief', 'correct_answer': 'True'},
{'question18': 'dauern', 'correct_answer': 'True'},
{'question19': 'eilig', 'correct_answer': 'True'},
{'question20': 'der Eintritt', 'correct_answer': 'True'},
{'question21': 'der Empfänger', 'correct_answer': 'True'},
{'question22': 'empfehlen', 'correct_answer': 'True'},
{'question23': 'das Ergebnis', 'correct_answer': 'True'},
{'question24': 'erlauben', 'correct_answer': 'True'},
{'question25': 'der Erwachsene', 'correct_answer': 'True'},
{'question26': 'ledig', 'correct_answer': 'True'},
{'question27': 'fehlen', 'correct_answer': 'True'},
Finished PROJECT
{'question0': 'Betreuung', 'correct_answer': 'True'},
{'question1': 'die Ankunft', 'correct_answer': 'True'},
{'question2': 'sich Anmelden', 'correct_answer': 'True'},
{'question3': 'die Auskunft', 'correct_answer': 'True'},
{'question4': 'die Beamtin', 'correct_answer': 'True'},
{'question5': 'bedeuten', 'correct_answer': 'True'},
{'question6': 'der Beruf', 'correct_answer': 'True'},
{'question7': 'der Blick', 'correct_answer': 'True'},
{'question8': 'breit', 'correct_answer': 'True'},
{'question9': 'der Empfänger', 'correct_answer': 'True'},
{'question10': 'empfehlen', 'correct_answer': 'True'},
{'question11': 'erlauben', 'correct_answer': 'True'},
Finished PROJECT
{'question0': 'Betreuung', 'correct_answer': 'True'},
{'question1': 'die Ankunft', 'correct_answer': 'True'},
{'question2': 'sich Anmelden', 'correct_answer': 'True'},
{'question3': 'die Ansage', 'correct_answer': 'True'},
{'question4': 'die Auskunft', 'correct_answer': 'True'},
{'question5': 'die Beamtin', 'correct_answer': 'True'},
{'question6': 'bedeuten', 'correct_answer': 'True'},
{'question7': 'der Beruf', 'correct_answer': 'True'},
{'question8': 'breit', 'correct_answer': 'True'},
{'question9': 'draussen', 'correct_answer': 'True'},
{'question10': 'erlauben', 'correct_answer': 'True'},
{'question11': 'ledig', 'correct_answer': 'True'},
Finished PROJECT
{'question0': 'die Auskunft', 'correct_answer': 'True'},
{'question1': 'bedeuten', 'correct_answer': 'True'},
{'question2': 'der Beruf', 'correct_answer': 'True'},
{'question3': 'breit', 'correct_answer': 'True'},
Finished PROJECT
{'question0': 'die Auskunft', 'correct_answer': 'True'},
{'question1': 'bedeuten', 'correct_answer': 'True'},
{'question2': 'der Beruf', 'correct_answer': 'True'},
Finished PROJECT
Finished PROJECT
{'question0': 'Geschlecht', 'correct_answer': 'True'},
{'question1': 'Beziehungen', 'correct_answer': 'True'},
{'question2': 'Gewohnheiten', 'correct_answer': 'True'},
{'question3': 'Einrichtungen', 'correct_answer': 'True'},
{'question4': 'Betreuung', 'correct_answer': 'True'},
{'question5': 'die Ankunft', 'correct_answer': 'True'},
{'question6': 'die Ansage', 'correct_answer': 'True'},
{'question7': 'der Anschluss', 'correct_answer': 'True'},
{'question8': 'die Auskunft', 'correct_answer': 'True'},
{'question9': 'die Beamtin', 'correct_answer': 'True'},
{'question10': 'bekannt', 'correct_answer': 'True'},
{'question11': 'besetzt', 'correct_answer': 'True'},
{'question12': 'Besichtigen', 'correct_answer': 'True'},
{'question13': 'leise', 'correct_answer': 'True'},
{'question14': 'der Blick', 'correct_answer': 'True'},
{'question15': 'breit', 'correct_answer': 'True'},
{'question16': 'die Durchsage', 'correct_answer': 'True'},
{'question17': 'eilig', 'correct_answer': 'True'},
{'question18': 'der Empfänger', 'correct_answer': 'True'},
{'question19': 'der Erwachsene', 'correct_answer': 'True'},
Finished PROJECT
{'question0': 'Geschlecht', 'correct_answer': 'True'},
{'question1': 'Beziehungen', 'correct_answer': 'True'},
{'question2': 'Staatsangehörigkeit', 'correct_answer': 'True'},
{'question3': 'Herkunft', 'correct_answer': 'True'},
{'question4': 'Tagesblauf', 'correct_answer': 'True'},
Finished PROJECT
{'question0': 'Einrichtungen', 'correct_answer': 'True'},
{'question1': 'Betreuung', 'correct_answer': 'True'},
{'question2': 'Lektüre', 'correct_answer': 'True'},
{'question3': 'die Ankunft', 'correct_answer': 'True'},
{'question4': 'die Ansage', 'correct_answer': 'True'},
{'question5': 'der Anschluss', 'correct_answer': 'True'},
{'question6': 'die Auskunft', 'correct_answer': 'True'},
{'question7': 'die Beamtin', 'correct_answer': 'True'},
{'question8': 'der Beruf', 'correct_answer': 'True'},
{'question9': 'leise', 'correct_answer': 'True'},
{'question10': 'der Blick', 'correct_answer': 'True'},
{'question11': 'breit', 'correct_answer': 'True'},
{'question12': 'der Brief', 'correct_answer': 'True'},
{'question13': 'draussen', 'correct_answer': 'True'},
{'question14': 'die Durchsage', 'correct_answer': 'True'},
{'question15': 'der Empfänger', 'correct_answer': 'True'},
{'question16': 'fehlen', 'correct_answer': 'True'},
{'question17': 'fremd', 'correct_answer': 'True'},
{'question18': 'Die Führung', 'correct_answer': 'True'},
{'question19': 'das Gewicht', 'correct_answer': 'True'},
{'question20': 'anhalten', 'correct_answer': 'True'},
{'question21': 'gültig', 'correct_answer': 'True'},
{'question22': 'Bekannt', 'correct_answer': 'True'},
{'question23': 'Kunde', 'correct_answer': 'True'},
{'question24': 'überweisen', 'correct_answer': 'True'},
{'question25': 'sich kümmern', 'correct_answer': 'True'},
{'question26': 'legen', 'correct_answer': 'True'},
{'question27': 'lustig', 'correct_answer': 'True'},
{'question28': 'möglich', 'correct_answer': 'True'},
{'question29': 'riechen', 'correct_answer': 'True'},
{'question30': 'das Schild', 'correct_answer': 'True'},
{'question31': 'die Sehenswürdigkeit', 'correct_answer': 'True'},
{'question32': 'rauchen', 'correct_answer': 'True'},
{'question33': 'selbständig', 'correct_answer': 'True'},
{'question34': 'unterschreiben', 'correct_answer': 'True'},
{'question35': 'verdienen', 'correct_answer': 'True'},
{'question36': 'der Verein, Sportverein', 'correct_answer': 'True'},
{'question37': 'der Verwandte', 'correct_answer': 'True'},
{'question38': 'sich vorstellen', 'correct_answer': 'True'},
{'question39': 'die Vorwahl', 'correct_answer': 'True'},
{'question40': 'weiblich', 'correct_answer': 'True'},
{'question41': 'wichtig', 'correct_answer': 'True'},
{'question42': 'der Wind', 'correct_answer': 'True'},
{'question43': 'zurzeit', 'correct_answer': 'True'},
{'question44': 'der Zoll', 'correct_answer': 'True'},
{'question45': 'zufrieden', 'correct_answer': 'True'},
Finished PROJECT
{'question0': 'Betreuung', 'correct_answer': 'True'},
{'question1': 'fremd', 'correct_answer': 'True'},
{'question2': 'Die Führung', 'correct_answer': 'True'},
{'question3': 'das Gewicht', 'correct_answer': 'True'},
{'question4': 'gültig', 'correct_answer': 'True'},
{'question5': 'lustig', 'correct_answer': 'True'},
{'question6': 'riechen', 'correct_answer': 'True'},
{'question7': 'selbständig', 'correct_answer': 'True'},
{'question8': 'der Verwandte', 'correct_answer': 'True'},
{'question9': 'die Vorwahl', 'correct_answer': 'True'},
{'question10': 'der Zoll', 'correct_answer': 'True'},
{'question11': 'zufrieden', 'correct_answer': 'True'},
Finished PROJECT
{'question0': 'selbständig', 'correct_answer': 'True'},
{'question1': 'der Verwandte', 'correct_answer': 'True'},
Finished PROJECT
{'question0': 'Gewohnheiten', 'correct_answer': 'True'},
{'question1': 'Betreuung', 'correct_answer': 'True'},
{'question2': 'leise', 'correct_answer': 'True'},
{'question3': 'Die Führung', 'correct_answer': 'True'},
{'question4': 'das Gewicht', 'correct_answer': 'True'},
{'question5': 'anhalten', 'correct_answer': 'True'},
{'question6': 'gültig', 'correct_answer': 'True'},
{'question7': 'Kunde', 'correct_answer': 'True'},
{'question8': 'überweisen', 'correct_answer': 'True'},
{'question9': 'sich kümmern', 'correct_answer': 'True'},
{'question10': 'legen', 'correct_answer': 'True'},
{'question11': 'riechen', 'correct_answer': 'True'},
{'question14': 'verdienen', 'correct_answer': 'True'},
{'question15': 'der Verwandte', 'correct_answer': 'True'},
{'question16': 'sich vorstellen', 'correct_answer': 'True'},
{'question17': 'die Vorwahl', 'correct_answer': 'True'},
{'question18': 'der Zoll', 'correct_answer': 'True'},
{'question19': 'zufrieden', 'correct_answer': 'True'},
{'question20': 'schaffe', 'correct_answer': 'True'},
{'question21': 'ansehen. Hat angesehen', 'correct_answer': 'True'},
{'question22': 'Ausruhen, hat ausgeruht', 'correct_answer': 'True'},
{'question23': 'Ausser, Ausserdem', 'correct_answer': 'True'},
{'question24': 'die Austellung', 'correct_answer': 'True'},
{'question25': 'Austragen, hat Ausgetragen', 'correct_answer': 'True'},
{'question26': 'beeilen sich, hat beeilt', 'correct_answer': 'True'},
{'question27': 'beeilen sich, hat beeilt', 'correct_answer': 'True'},
{'question28': 'Begründen. Hat begründet', 'correct_answer': 'True'},
{'question29': 'Beraten. Hat berat', 'correct_answer': 'True'},
{'question30': 'Berichten. Hat berichtet', 'correct_answer': 'True'},
{'question31': 'der Bescheid', 'correct_answer': 'True'},
{'question32': 'Beschreiben, hat beschrieben', 'correct_answer': 'True'},
{'question33': 'Beschweren, hat beschwert', 'correct_answer': 'True'},
{'question34': 'Bestätigen, hat bestätigt', 'correct_answer': 'True'},
{'question35': 'Bestehen, hat bestanden', 'correct_answer': 'True'},
{'question36': 'Bewerben um, hat beworben', 'correct_answer': 'True'},
{'question37': 'blöd', 'correct_answer': 'True'},
{'question38': 'Die Bohne', 'correct_answer': 'True'},
{'question39': 'Morgen buche ich unsere Urlaubsreise. Hat gebucht', 'correct_answer': 'True'},
{'question40': 'Bunt ', 'correct_answer': 'True'},
Finished PROJECT
{'question0': 'anhalten', 'correct_answer': 'True'},
{'question1': 'legen', 'correct_answer': 'True'},
{'question2': 'der Verwandte', 'correct_answer': 'True'},
{'question3': 'sich vorstellen', 'correct_answer': 'True'},
{'question4': 'Bewerben um, hat beworben', 'correct_answer': 'True'},
Finished PROJECT
{'question0': 'Beziehungen', 'correct_answer': 'True'},
{'question1': 'Einrichtungen', 'correct_answer': 'True'},
{'question2': 'Betreuung', 'correct_answer': 'True'},
{'question3': 'die Ankunft', 'correct_answer': 'True'},
{'question4': 'die Ansage', 'correct_answer': 'True'},
{'question5': 'die Auskunft', 'correct_answer': 'True'},
{'question6': 'kriegen', 'correct_answer': 'True'},
{'question7': 'sich kümmern', 'correct_answer': 'True'},
{'question8': 'legen', 'correct_answer': 'True'},
{'question9': 'riechen', 'correct_answer': 'True'},
{'question10': 'selbständig', 'correct_answer': 'True'},
{'question11': 'verdienen', 'correct_answer': 'True'},
{'question12': 'der Verein, Sportverein', 'correct_answer': 'True'},
{'question13': 'der Verwandte', 'correct_answer': 'True'},
{'question14': 'die Vorsicht', 'correct_answer': 'True'},
{'question15': 'die Vorsicht', 'correct_answer': 'True'},
{'question16': 'sich vorstellen', 'correct_answer': 'True'},
{'question17': 'weiblich', 'correct_answer': 'True'},
{'question18': 'der Zoll', 'correct_answer': 'True'},
{'question19': 'zufrieden', 'correct_answer': 'True'},
{'question20': 'schaffe', 'correct_answer': 'True'},
{'question21': 'fängt an, hat angefangen', 'correct_answer': 'True'},
{'question22': 'ansehen. Hat angesehen', 'correct_answer': 'True'},
{'question23': 'aufräumen, hat aufgeräumt', 'correct_answer': 'True'},
{'question24': 'Ausruhen, hat ausgeruht', 'correct_answer': 'True'},
{'question25': 'Aussehen, hat ausgesehen', 'correct_answer': 'True'},
{'question26': 'Aussprechen, hat ausgesprochen', 'correct_answer': 'True'},
{'question27': 'die Austellung', 'correct_answer': 'True'},
{'question28': 'Austragen, hat Ausgetragen', 'correct_answer': 'True'},
{'question29': 'Baden, hat gebadet', 'correct_answer': 'True'},
{'question30': 'Die Kinder haben etwas gebastellt', 'correct_answer': 'True'},
{'question31': 'Bauen, hat gebaut', 'correct_answer': 'True'},
{'question32': 'beeilen sich, hat beeilt', 'correct_answer': 'True'},
{'question33': 'Begründen. Hat begründet', 'correct_answer': 'True'},
{'question34': 'Beraten. Hat berat', 'correct_answer': 'True'},
{'question35': 'Berichten. Hat berichtet', 'correct_answer': 'True'},
{'question36': 'der Bescheid', 'correct_answer': 'True'},
{'question37': 'Beschreiben, hat beschrieben', 'correct_answer': 'True'},
{'question38': 'Beschweren, hat beschwert', 'correct_answer': 'True'},
Finished PROJECT
{'question0': 'Geschlecht', 'correct_answer': 'True'},
